services:
  app:
    build: .
    env_file: .env
    volumes:
      # - "./static:/app/static/"
      # - "./media:/app/media"
      # - "./db:/app/db"
      - "./:/app"
    command: "sh /app/entrypoint.sh"
    ports:
      - 5555:8000

  celery_worker:
    build: .
    env_file: .env
    volumes:
      # - "./static:/app/static/"
      # - "./media:/app/media"
      # - "./db:/app/db"
      - "./:/app"
    command: "sh celery/worker/entrypoint.sh"

  redis:
    image: redis
