# Generated by Django 5.0.3 on 2024-03-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30, verbose_name="Название")),
                ("description", models.TextField(verbose_name="Описание")),
                ("address", models.CharField(max_length=50, verbose_name="Адресс")),
                (
                    "postcode",
                    models.PositiveIntegerField(verbose_name="Почтовый индекс"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30, verbose_name="Название")),
                ("description", models.TextField(verbose_name="Описание")),
                ("image", models.ImageField(upload_to="", verbose_name="Изображение")),
                ("date", models.DateField(verbose_name="Дата")),
                (
                    "organizations",
                    models.ManyToManyField(
                        related_name="events", to="main.organization"
                    ),
                ),
            ],
        ),
    ]
