# Generated by Django 5.0.3 on 2024-03-09 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_organization_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="image",
            field=models.ImageField(
                null=True, upload_to="", verbose_name="Изображение"
            ),
        ),
    ]
